# Generated by Django 2.2.4 on 2019-08-21 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moment',
            name='kind',
            field=models.CharField(choices=[('Python技术', 'Python技术'), ('数据库技术', '数据库技术'), ('经济学', '经济学'), ('文体资讯', '文体资讯'), ('个人心情', '个人心情'), ('其他', '其他')], default=('Python技术', 'Python技术'), max_length=20),
        ),
    ]
